"""initial migration

Revision ID: 686eef07eead
Revises: 
Create Date: 2025-01-24 10:52:21.888676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '686eef07eead'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('birds', sa.Column('image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('birds', 'image')
    # ### end Alembic commands ###
